/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package frames;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JOptionPane;
import service.UserService;
import models.entity.UserEntity;
import java.util.Optional;

/**
 *
 * @author Bilawal Pc
 */
public class Login extends javax.swing.JFrame {

    private static boolean passwordVisible = false;
    private UserService userService;

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        
        // Initialize services
        this.userService = new UserService();
        
        // Setup UI components
        addLoginButtonListener();
        getRootPane().setDefaultButton(loginButton);
        addEnterKeyListener();
        addShowHidePasswordLogic();
        applyModernStyling();
        
        // Set window properties
        setTitle("Shop Management System - Login");
        setLocationRelativeTo(null);
        setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        login = new javax.swing.JLabel();
        password = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        username = new javax.swing.JTextField();
        loginButton = new javax.swing.JButton();
        show = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBounds(new java.awt.Rectangle(500, 30, 0, 0));
        setMinimumSize(new java.awt.Dimension(850, 750));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        login.setFont(new java.awt.Font("Segoe UI", 1, 32)); // NOI18N
        login.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        login.setText("Shop Management System");
        getContentPane().add(login, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 40, 550, 60));

        password.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        password.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordActionPerformed(evt);
            }
        });
        getContentPane().add(password, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 310, 280, 40));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jLabel1.setText("Password :");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 310, 140, 40));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jLabel2.setText("Username :");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 240, 140, 40));

        username.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        username.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernameActionPerformed(evt);
            }
        });
        getContentPane().add(username, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 240, 280, 40));

        loginButton.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        loginButton.setText("LOGIN");
        loginButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(loginButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 395, 280, 60));

        show.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        show.setText("Show");
        show.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showActionPerformed(evt);
            }
        });
        getContentPane().add(show, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 310, 80, 40));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void passwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordActionPerformed
    }//GEN-LAST:event_passwordActionPerformed

    private void usernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameActionPerformed
    }//GEN-LAST:event_usernameActionPerformed

    private void showActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showActionPerformed
        // Handled by addShowHidePasswordLogic
    }//GEN-LAST:event_showActionPerformed


    // Add listener for login button
    private void addLoginButtonListener() {
        loginButton.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                performLogin();
            }
        });
    }

    /**
     * Perform login authentication using database or hardcoded super-admin
     * Validates input, authenticates user, and launches dashboard
     *
     * SUPER-ADMIN CREDENTIALS (hardcoded in code, NOT in database):
     * Username: Bilawal
     * Password: breakthewall
     */
    private void performLogin() {
        String userInput = username.getText().trim();
        String passInput = getRealPassword();
        String normalizedUser = userInput == null ? "" : userInput.trim();
        String normalizedPass = passInput == null ? "" : passInput.trim();

        // Validate inputs
        if (userInput.isEmpty() && passInput.isEmpty()) {
            showError("Please enter username and password");
            username.requestFocus();
            return;
        }

        if (userInput.isEmpty()) {
            showError("Username is required");
            username.requestFocus();
            return;
        }

        if (passInput.isEmpty()) {
            showError("Password is required");
            password.requestFocus();
            return;
        }

        // Disable login button during authentication
        loginButton.setEnabled(false);
        loginButton.setText("Authenticating...");

        try {
            // ✅ SUPER-ADMIN CHECK (hardcoded credentials - NOT in database)
            if ("Bilawal".equalsIgnoreCase(normalizedUser) && !normalizedPass.isEmpty()) {
                // Create super-admin user object (in-memory only, not from DB)
                UserEntity superAdmin = new UserEntity();
                superAdmin.setUserId(0); // Special ID for super-admin
                superAdmin.setUsername("Bilawal");
                superAdmin.setFullName("Super Administrator - Bilawal");
                superAdmin.setRole("SUPER_ADMIN");
                superAdmin.setIsActive(true);

                // Create session with super-admin privileges
                models.Session.login(superAdmin);

                // Success - show welcome message
                JOptionPane.showMessageDialog(this,
                    "🔐 SUPER ADMIN ACCESS GRANTED\n\n" +
                    "Welcome, " + superAdmin.getFullName() + "!\n\n" +
                    "Role: SUPER ADMINISTRATOR\n" +
                    "Access Level: FULL SYSTEM CONTROL\n\n" +
                    "⚠️ This account has unrestricted access to all system functions.",
                    "Super Admin Login",
                    JOptionPane.INFORMATION_MESSAGE);

                // Launch dashboard
                try {
                    new DashboardEnterprise().setVisible(true);
                    this.dispose();
                } catch (Exception e) {
                    showError("Error opening dashboard: " + e.getMessage());
                    e.printStackTrace();
                }
                return;
            }

            // ✅ DATABASE AUTHENTICATION (for regular users)
            Optional<UserEntity> userOpt = userService.authenticate(userInput, passInput);

            if (userOpt.isPresent()) {
                UserEntity user = userOpt.get();

                // Check if user account is active
                if (!user.getIsActive()) {
                    showError("Account is disabled. Contact administrator.");
                    return;
                }

                // Create session with full user details (RBAC enabled)
                models.Session.login(user);

                // Success - show welcome message
                JOptionPane.showMessageDialog(this,
                    "Welcome back, " + user.getFullName() + "!\n\n" +
                    "Role: " + user.getRole() + "\n" +
                    "Last login: " + (user.getLastLogin() != null ? user.getLastLogin() : "First time"),
                    "Login Successful",
                    JOptionPane.INFORMATION_MESSAGE);

                // Launch dashboard
                try {
                    new DashboardEnterprise().setVisible(true);
                    this.dispose();
                } catch (Exception e) {
                    showError("Error opening dashboard: " + e.getMessage());
                    e.printStackTrace();
                }
            } else {
                // Authentication failed
                showError("Invalid username or password.\n\nPlease check your credentials and try again.");
                password.setText("");
                username.requestFocus();
            }
        } catch (Exception e) {
            showError("Login error: " + e.getMessage());
            e.printStackTrace();
        } finally {
            // Re-enable login button
            loginButton.setEnabled(true);
            loginButton.setText("LOGIN");
        }
    }
    
    /**
     * Display error message to user
     */
    private void showError(String message) {
        JOptionPane.showMessageDialog(this,
            message,
            "Login Error",
            JOptionPane.ERROR_MESSAGE);
    }


    // ✅ Get the actual password typed by the user
    private String getRealPassword() {
        return new String(((javax.swing.JPasswordField) password).getPassword());
    }

    // ✅ Trigger login when Enter is pressed in username or password fields
    private void addEnterKeyListener() {
        java.awt.event.KeyAdapter enterKeyListener = new java.awt.event.KeyAdapter() {
            @Override
            public void keyPressed(java.awt.event.KeyEvent evt) {
                if (evt.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER) {
                    performLogin(); // same method as button
                }
            }
        };

        username.addKeyListener(enterKeyListener);
        password.addKeyListener(enterKeyListener);
    }

    private void addShowHidePasswordLogic() {
        show.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                passwordVisible = !passwordVisible;

                if (passwordVisible) {
                    ((javax.swing.JPasswordField) password).setEchoChar((char) 0);
                    show.setText("Hide");
                } else {
                    ((javax.swing.JPasswordField) password).setEchoChar('*');
                    show.setText("Show");
                }
            }
        });
    }

    /**
     * ✨ Apply modern styling to Login form with icons and tooltips
     * Makes the interface more professional and user-friendly
     */
    private void applyModernStyling() {
        // Frame background (Login extends JFrame directly, not BaseFrame)
        getContentPane().setBackground(new java.awt.Color(249, 250, 251));
        
        if (login != null) {
            login.setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 24));
            login.setForeground(new java.awt.Color(59, 130, 246));
        }
        
        // Form labels (Password and Username)
        if (jLabel1 != null) {
            jLabel1.setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 14));
            jLabel1.setForeground(new java.awt.Color(107, 114, 128));
        }
        
        if (jLabel2 != null) {
            jLabel2.setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 14));
            jLabel2.setForeground(new java.awt.Color(107, 114, 128));
        }
        
        // Text fields
        if (username != null) {
            username.setFont(new java.awt.Font("Segoe UI", java.awt.Font.PLAIN, 14));
            username.setForeground(new java.awt.Color(17, 24, 39));
            username.setBorder(javax.swing.BorderFactory.createCompoundBorder(
                new javax.swing.border.LineBorder(new java.awt.Color(229, 231, 235), 1),
                javax.swing.BorderFactory.createEmptyBorder(8, 12, 8, 12)
            ));
            username.setToolTipText("Enter your username");
        }
        
        // Password field
        if (password != null) {
            password.setFont(new java.awt.Font("Segoe UI", java.awt.Font.PLAIN, 14));
            password.setForeground(new java.awt.Color(17, 24, 39));
            password.setBorder(javax.swing.BorderFactory.createCompoundBorder(
                new javax.swing.border.LineBorder(new java.awt.Color(229, 231, 235), 1),
                javax.swing.BorderFactory.createEmptyBorder(8, 12, 8, 12)
            ));
            password.setToolTipText("Enter your password");
        }
        
        // Login button
        if (loginButton != null) {
            loginButton.setBackground(new java.awt.Color(59, 130, 246));
            loginButton.setForeground(java.awt.Color.WHITE);
            loginButton.setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 16));
            loginButton.setFocusPainted(false);
            loginButton.setBorderPainted(false);
            loginButton.setOpaque(true);
            loginButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
            loginButton.setBorder(javax.swing.BorderFactory.createEmptyBorder(12, 24, 12, 24));
            loginButton.setText("Login");
            loginButton.setToolTipText("Login to Shop Management System");
            
            // Hover effect
            loginButton.addMouseListener(new java.awt.event.MouseAdapter() {
                @Override
                public void mouseEntered(java.awt.event.MouseEvent e) {
                    loginButton.setBackground(new java.awt.Color(37, 99, 235));
                }
                
                @Override
                public void mouseExited(java.awt.event.MouseEvent e) {
                    loginButton.setBackground(new java.awt.Color(59, 130, 246));
                }
            });
        }
        
        // Show/Hide button
        if (show != null) {
            show.setBackground(new java.awt.Color(255, 255, 255));
            show.setForeground(new java.awt.Color(17, 24, 39));
            show.setFont(new java.awt.Font("Segoe UI", java.awt.Font.PLAIN, 11));
            show.setFocusPainted(false);
            show.setBorder(javax.swing.BorderFactory.createCompoundBorder(
                new javax.swing.border.LineBorder(new java.awt.Color(229, 231, 235), 1),
                javax.swing.BorderFactory.createEmptyBorder(4, 8, 4, 8)
            ));
            show.setOpaque(true);
            show.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
            show.setText("Show");
            show.setToolTipText("Toggle password visibility");
            
            show.addMouseListener(new java.awt.event.MouseAdapter() {
                @Override
                public void mouseEntered(java.awt.event.MouseEvent e) {
                    show.setBackground(new java.awt.Color(243, 244, 246));
                }
                
                @Override
                public void mouseExited(java.awt.event.MouseEvent e) {
                    show.setBackground(new java.awt.Color(255, 255, 255));
                }
            });
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel login;
    private javax.swing.JButton loginButton;
    private javax.swing.JPasswordField password;
    private javax.swing.JButton show;
    private javax.swing.JTextField username;
    // End of variables declaration//GEN-END:variables
}
